apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenwebapprc
  namespace: test-ns
  #lables:
    #app: mavenwebapp
spec:
  replicas: 1
  selector:
    app: mavenwebapp
  template:
    metadata:
      name: mavenwebapp
      lables:
        app: javawebapp
    spec:
      containers:
       - name: mavenwebapp
        image: harishkumarbr/maven-web-application:${buildNumber}
        ports:
         - containerPort: 8080
          name: accessport
     # - name: javawebapp
      #  image: harishkumarbr/java-web-app-docker:10
       # ports:
        # - containerPort: 8080        
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: test-ns
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 30790
